badge = "f"
artifact_url = "https://github.com/jlohmoeller/fecad"
cd = "c"
citation = "@INPROCEEDINGS{lohmoeller2026rethinking,\n  author={Lohm{\\\"o}ller, Johannes and Wehrle, Klaus and Pennekamp, Jan},\n  booktitle={2026 IEEE Annual Computer Security Applications Conference (ACSAC)}, \n  title={Rethinking Secure Patient Discovery: Matching Federation with Fine-Grained Consent}, \n  year={2026}}"
license_url = "https://mit-license.org/"
infrastructure_url = "https://cloudlab.org"
infrastructure_resources = "https://github.com/jlohmoeller/fecad/blob/main/infrastructure/README.txt"
infrastructure_allocation = ""
install_script = "https://github.com/jlohmoeller/fecad/blob/main/install.sh"
use = "Evaluating at full scope or with the original datasets (access restricted) is beyond the scope of this artifact. Not intended for production use either in its current form"
destructive = ""
claim1 = "https://github.com/jlohmoeller/fecad/blob/main/claims/01-backend-comparison/claim.txt"
script1 = "https://github.com/jlohmoeller/fecad/blob/main/claims/01-backend-comparison/run.sh"
expected1 = "https://github.com/jlohmoeller/fecad/blob/main/claims/01-backend-comparison/expected/scale1.txt"
claim2 = "https://github.com/jlohmoeller/fecad/blob/main/claims/02-records-per-provider/claim.txt"
script2 = "https://github.com/jlohmoeller/fecad/blob/main/claims/02-records-per-provider/run.sh"
expected2 = "https://github.com/jlohmoeller/fecad/blob/main/claims/02-records-per-provider/expected/scale1.txt"
claim3 = "https://github.com/jlohmoeller/fecad/blob/main/claims/03-number-of-providers/claim.txt"
script3 = "https://github.com/jlohmoeller/fecad/blob/main/claims/03-number-of-providers/run.sh"
expected3 = "https://github.com/jlohmoeller/fecad/blob/main/claims/03-number-of-providers/expected/scale1.txt"
claim4 = "https://github.com/jlohmoeller/fecad/blob/main/claims/04-dataset-diversity/claim.txt"
script4 = "https://github.com/jlohmoeller/fecad/blob/main/claims/04-dataset-diversity/run.sh"
expected4 = "https://github.com/jlohmoeller/fecad/blob/main/claims/04-dataset-diversity/expected/scale1.txt"
hw = ""
sw = ""
api = ""
gui = "n"
readme = "https://github.com/jlohmoeller/fecad/blob/main/README.txt"
